name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ ubuntu, macOS, windows ]
        include:
          - os: ubuntu
            image: ubuntu-latest
          - os: windows
            image: windows-latest
          - os: macOS
            image: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry and dependencies
      uses: ./.github/actions/bootstrap-poetry
      with:
        os: ${{ matrix.os }}

    - name: Check quality
      run: |
        poetry run pre-commit run --all-files

    - name: Check tests
      run: |
        poetry run pytest tests/ --cov=src
        poetry run mypy

    - name: Publish coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
      run: |
        pip install coveralls
        coveralls --service=github
